version: '2.2'

services:
    telemac-mascaret:
        image: flussplan/telemac:v8-latest
        stdin_open: true
        tty: true
        cpu_count: 0
        volumes:
            - ./workdir:/opt/telemac-mascaret/latest/workdir

        # Optionally pass in a custom configuration file mounting like this:

            #- ./workdir/my-systel.cfg:/opt/telemac-mascaret/systel.cfg

        # Enable the following options to access the distribution files (examples, docs, etc.)
        # via https://localhost:8090
        
        #environment:
        #    ENABLE_WEB_BROWSER: 1
        #ports:
        #    - 8090:80